import unittest
import copy

import numpy as np
from scipy import stats


from pyapprox.surrogates.affine.induced import (
    GaussQuadratureBasedDiscreteInducedPolySampler,
    PolynomialChaosExpansion,
)
from pyapprox.surrogates.affine.basis import OrthonormalPolynomialBasis
from pyapprox.surrogates.univariate.orthopoly import (
    setup_univariate_orthogonal_polynomial_from_marginal,
)
from pyapprox.variables.joint import IndependentMarginalsVariable
from pyapprox.surrogates.affine.linearsystemsolvers import LstSqSolver
from pyapprox.util.backends.numpy import NumpyMixin
from pyapprox.util.backends.torch import TorchMixin


class TestDiscreteInducedPolySampler:
    def setUp(self):
        np.random.seed(1)

    def _setup_sampler(self, nvars, degree):
        bkd = self.get_backend()
        # Setup PolynomialChaosExpansion
        marginals = [stats.uniform(0, 1) for ii in range(nvars)]
        polys_1d = [
            setup_univariate_orthogonal_polynomial_from_marginal(
                marginal, backend=bkd
            )
            for marginal in marginals
        ]
        variable = IndependentMarginalsVariable(marginals, backend=bkd)
        basis = OrthonormalPolynomialBasis(polys_1d)
        basis.set_hyperbolic_indices(degree, 1.0)
        bexp = PolynomialChaosExpansion(basis)

        # Initialize the sampler
        sampler = GaussQuadratureBasedDiscreteInducedPolySampler(
            bexp, variable, [500] * nvars
        )
        return sampler, variable

    def _check_moments_of_induced_measure_samples(self, nvars, degree):
        """
        Test that the moments of the samples generated by __call__ match the
        moments computed by sampling the true induced measure.
        """
        bkd = self.get_backend()
        nsamples = int(1e5)  # Number of samples to generate
        sampler, variable = self._setup_sampler(nvars, degree)
        samples = sampler(nsamples)

        # Compute moments from generated samples
        sample_mean = bkd.mean(samples, axis=1)
        sample_variance = bkd.var(samples, axis=1)

        # Compute moments from the true induced measure
        random_samples = variable.rvs(1e5)

        # sample christoffel function and not induced
        # measure because quadrature rule encodes the variable.pdf
        christoffel_vals = sampler.christoffel_function(random_samples)
        true_mean = bkd.mean(random_samples * christoffel_vals[:, 0], axis=1)
        true_variance = (
            bkd.mean(random_samples**2 * christoffel_vals[:, 0], axis=1)
            - true_mean**2
        )

        # Check that the moments match within a tolerance
        assert bkd.allclose(sample_mean, true_mean, rtol=1e-2, atol=1e-2)
        assert bkd.allclose(
            sample_variance, true_variance, rtol=1e-2, atol=1e-2
        )

    def test_moments_of_induced_measure_samples(self):
        test_cases = [[2, 10], [3, 2]]
        for test_case in test_cases:
            self._check_moments_of_induced_measure_samples(*test_case)

    def test_weighted_lstsq_solver(self):
        bkd = self.get_backend()
        nvars, degree = 2, 5
        sampler, variable = self._setup_sampler(nvars, degree)
        poly = sampler.poly()

        # generate training data
        nsamples = int(1e2)  # Number of samples to generate
        true_coef = bkd.asarray(np.random.normal(0, 1, (poly.nterms(), 1)))
        true_poly = copy.deepcopy(poly)
        true_poly.set_coefficients(true_coef)
        train_samples = sampler(nsamples)
        train_values = true_poly(train_samples)
        solver = LstSqSolver(backend=bkd)
        solver.set_weights(sampler.christoffel_function(train_samples))
        poly.set_solver(solver)
        poly.fit(train_samples, train_values)
        assert bkd.allclose(poly.get_coefficients(), true_coef)


class TestNumpyDiscreteInducedPolySampler(
    TestDiscreteInducedPolySampler, unittest.TestCase
):
    def get_backend(self):
        return NumpyMixin


class TestTorchDiscreteInducedPolySampler(
    TestDiscreteInducedPolySampler, unittest.TestCase
):
    def get_backend(self):
        return TorchMixin


if __name__ == "__main__":
    unittest.main()
