name: pyapprox-base
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - numpy>=2.0
  - matplotlib
  - scipy
  - jupyter
  - pytest
  - coverage>=6.4
  - pytest-cov
  - pip
  - setuptools
  - sympy
  - networkx
  - pytorch>=2.5
  - numba
  - cvxpy
  # make html in docs folder
  - sphinx
  - sphinx-gallery
  - pip:
    - scikit-fem
    - sphinx_copybutton
    - sphinx_rtd_theme
    - numpydoc
    - sphinx_automodapi
    - umbridge
