r"""Tests for fitting a latent map by gradient descent.

The load-bearing test is the equivalence one: this fitter and the
closed-form solver minimize the *same* objective, differing only in how
they reach it, so on a map that is linear in its parameters they must
arrive at the same place. That checks the optimizer against an exact
reference rather than against a tolerance someone chose by running it.

The rest pin what the optimizer seam buys -- that a different
``torch.optim`` class can be chosen without a new fitter, and that
chaining a polish after a first-order stage is expressible.
"""

import numpy as np
import pytest
import torch
from pyapprox.surrogates.operatorlearning import (
    IdentityFieldEncoder,
    WeightedLeastSquaresOperatorFitter,
)
from pyapprox.surrogates.operatorlearning.latent_maps import (
    ChainedTorchOptimizer,
    MLPLatentMap,
    TorchGradientLatentMapFitter,
    TorchOptimizerSpec,
    torch_adam,
    torch_lbfgs,
)
from pyapprox.util.backends.numpy import NumpyBkd
from pyapprox.util.backends.protocols import Backend


def _affine_data(bkd: Backend, nsamples: int = 200, seed: int = 0):
    """Data generated by an affine map, so a least-squares fit is exact."""
    rng = np.random.RandomState(seed)
    matrix = rng.normal(0.0, 1.0, (2, 3))
    offset = rng.normal(0.0, 1.0, (2, 1))
    codes_in = rng.uniform(-1.0, 1.0, (3, nsamples))
    codes_out = matrix @ codes_in + offset
    return (
        bkd.asarray(codes_in),
        bkd.asarray(codes_out),
        matrix,
        offset,
    )


def _fitter(torch_bkd: Backend, optimizer=None, **kwargs):
    return TorchGradientLatentMapFitter(
        IdentityFieldEncoder(3, torch_bkd),
        IdentityFieldEncoder(2, torch_bkd),
        torch_bkd,
        optimizer=optimizer,
        seed=0,
        **kwargs,
    )


def _max_residual(bkd: Backend, surrogate, codes_in, codes_out) -> float:
    return float(bkd.max(bkd.abs(surrogate(codes_in) - codes_out)))


class TestAgreementWithTheClosedFormSolver:
    r"""Same objective, two routes to it, so they must agree.

    Both minimize :math:`\sum_i \|g(\hat f^i) - \hat g^i\|_2^2`. One
    solves it directly, the other descends. On a latent map that is
    linear in its parameters the minimizer is unique, so a gradient fit
    that has converged reaches it -- and that is what makes this an
    exact check rather than a tolerance.
    """

    def test_recovers_the_generating_map(
        self, torch_bkd: Backend
    ) -> None:
        """An affine map on affine data: the fit should be exact."""
        codes_in, codes_out, matrix, _ = _affine_data(torch_bkd)
        surrogate = _fitter(torch_bkd).fit_encoded(
            MLPLatentMap(3, 2, [], torch_bkd), codes_in, codes_out
        )
        assert (
            _max_residual(torch_bkd, surrogate, codes_in, codes_out)
            < 1e-8
        )
        weight = next(surrogate.latent_map().parameters())
        torch_bkd.assert_allclose(
            weight, torch_bkd.asarray(matrix), atol=1e-8
        )

    def test_matches_least_squares_on_inconsistent_data(
        self, torch_bkd: Backend
    ) -> None:
        """The case with no exact solution, where the two could differ.

        With data outside the affine span there is a unique minimizer
        rather than an interpolant, so agreeing on it is a stronger
        claim than agreeing on a residual both drive to zero. The
        reference is the closed-form solver's own answer on the same
        data.
        """
        rng = np.random.RandomState(1)
        codes_in = torch_bkd.asarray(rng.uniform(-1.0, 1.0, (3, 120)))
        # Quadratic targets cannot be represented by an affine map.
        squared = torch_bkd.to_numpy(codes_in) ** 2
        codes_out = torch_bkd.asarray(squared[:2] + 0.5 * squared[1:])

        gradient_fit = _fitter(torch_bkd).fit_encoded(
            MLPLatentMap(3, 2, [], torch_bkd), codes_in, codes_out
        )

        reference = _least_squares_affine_fit(
            torch_bkd, codes_in, codes_out
        )
        torch_bkd.assert_allclose(
            gradient_fit(codes_in), reference, atol=1e-7
        )


def _least_squares_affine_fit(bkd: Backend, codes_in, codes_out):
    """Return the closed-form affine least-squares prediction.

    Uses the package's own solver over a degree-one expansion rather
    than a hand-rolled normal-equation solve, so the comparison is
    against the code that ships.
    """
    from pyapprox.probability import UniformMarginal
    from pyapprox.surrogates.affine.basis.orthonormal_poly import (
        OrthonormalPolynomialBasis,
    )
    from pyapprox.surrogates.affine.expansions.pce import (
        PolynomialChaosExpansion,
    )
    from pyapprox.surrogates.affine.univariate.factory import (
        create_bases_1d,
    )

    nvars = int(codes_in.shape[0])
    marginals = [UniformMarginal(-1.0, 1.0, bkd) for _ in range(nvars)]
    basis = OrthonormalPolynomialBasis(
        create_bases_1d(marginals, bkd), bkd
    )
    indices = np.vstack(
        [np.zeros((1, nvars), dtype=int), np.eye(nvars, dtype=int)]
    ).T
    basis.set_indices(bkd.asarray(indices, dtype=bkd.int64_dtype()))
    expansion = PolynomialChaosExpansion(
        basis, bkd, nqoi=int(codes_out.shape[0])
    )
    result = WeightedLeastSquaresOperatorFitter(
        IdentityFieldEncoder(nvars, bkd),
        IdentityFieldEncoder(int(codes_out.shape[0]), bkd),
        bkd,
    ).fit_encoded(expansion, codes_in, codes_out)
    return result.surrogate()(codes_in)


class TestTheOptimizerSeam:
    """A different optimizer needs no new fitter."""

    def test_adam_alone_runs(self, torch_bkd: Backend) -> None:
        codes_in, codes_out, _, _ = _affine_data(torch_bkd)
        surrogate = _fitter(
            torch_bkd,
            optimizer=torch_adam(learning_rate=0.05, nsteps=2000),
        ).fit_encoded(
            MLPLatentMap(3, 2, [], torch_bkd), codes_in, codes_out
        )
        assert surrogate(codes_in).shape == (2, 200)

    def test_lbfgs_alone_runs(self, torch_bkd: Backend) -> None:
        codes_in, codes_out, _, _ = _affine_data(torch_bkd)
        surrogate = _fitter(
            torch_bkd, optimizer=torch_lbfgs(nsteps=300)
        ).fit_encoded(
            MLPLatentMap(3, 2, [], torch_bkd), codes_in, codes_out
        )
        assert (
            _max_residual(torch_bkd, surrogate, codes_in, codes_out)
            < 1e-8
        )

    def test_an_arbitrary_torch_optimizer_runs(
        self, torch_bkd: Backend
    ) -> None:
        """The point of taking a spec rather than a learning rate.

        SGD's ``momentum`` has no counterpart in Adam's signature, so a
        fitter exposing per-optimizer knobs directly could not express
        this without growing a union of every optimizer's arguments.
        """
        codes_in, codes_out, _, _ = _affine_data(torch_bkd)
        spec = TorchOptimizerSpec(
            torch.optim.SGD, nsteps=500, lr=1e-3, momentum=0.9
        )
        surrogate = _fitter(torch_bkd, optimizer=spec).fit_encoded(
            MLPLatentMap(3, 2, [], torch_bkd), codes_in, codes_out
        )
        assert surrogate(codes_in).shape == (2, 200)

    def test_the_polish_improves_on_its_first_stage(
        self, torch_bkd: Backend
    ) -> None:
        r"""Why the default is a chain rather than Adam alone.

        Adam has no line search, so its step size is set by the
        gradient's running magnitude rather than by the objective. Near
        an exact fit the gradient is numerical noise and the steps stay
        full-sized, which walks the iterate back out of the optimum.
        L-BFGS has a line search and settles it.

        Compared against the same Adam configuration rather than a
        threshold, so what is asserted is that the second stage helps.
        """
        codes_in, codes_out, _, _ = _affine_data(torch_bkd)
        adam_only = torch_adam(learning_rate=0.05, nsteps=4000)
        chained = ChainedTorchOptimizer(
            [
                torch_adam(learning_rate=0.05, nsteps=4000),
                torch_lbfgs(nsteps=100),
            ]
        )
        errors = []
        for optimizer in (adam_only, chained):
            surrogate = _fitter(
                torch_bkd, optimizer=optimizer
            ).fit_encoded(
                MLPLatentMap(3, 2, [], torch_bkd), codes_in, codes_out
            )
            errors.append(
                _max_residual(
                    torch_bkd, surrogate, codes_in, codes_out
                )
            )
        assert errors[1] < errors[0]

    def test_the_default_chain_beats_its_first_stage_alone(
        self, torch_bkd: Backend
    ) -> None:
        """Passing no optimizer gets the chain, not bare Adam.

        Asserted through behaviour rather than by counting the stages,
        which would pin an implementation detail: what matters is that
        the default converges better than its first stage does alone.
        """
        codes_in, codes_out, _, _ = _affine_data(torch_bkd)
        default = _fitter(torch_bkd).fit_encoded(
            MLPLatentMap(3, 2, [], torch_bkd), codes_in, codes_out
        )
        first_stage_only = _fitter(
            torch_bkd, optimizer=torch_adam(nsteps=1000)
        ).fit_encoded(
            MLPLatentMap(3, 2, [], torch_bkd), codes_in, codes_out
        )
        assert _max_residual(
            torch_bkd, default, codes_in, codes_out
        ) < _max_residual(
            torch_bkd, first_stage_only, codes_in, codes_out
        )


class TestLeavesItsArgumentAlone:
    def test_fits_a_copy(self, torch_bkd: Backend) -> None:
        """So one untrained map can seed several fits."""
        codes_in, codes_out, _, _ = _affine_data(torch_bkd)
        template = MLPLatentMap(3, 2, [], torch_bkd)
        before = next(template.parameters()).detach().clone()
        surrogate = _fitter(torch_bkd).fit_encoded(
            template, codes_in, codes_out
        )
        torch_bkd.assert_allclose(
            next(template.parameters()), before, atol=0.0
        )
        assert surrogate.latent_map() is not template


class TestRejects:
    def test_rejects_a_non_torch_backend(self) -> None:
        with pytest.raises(TypeError, match="TorchBkd"):
            TorchGradientLatentMapFitter(
                IdentityFieldEncoder(3, NumpyBkd()),
                IdentityFieldEncoder(2, NumpyBkd()),
                NumpyBkd(),
            )

    def test_rejects_a_non_isometric_output_encoder(
        self, torch_bkd: Backend
    ) -> None:
        """This fitter reads a coefficient residual as a field error."""
        codes_in, codes_out, _, _ = _affine_data(torch_bkd)
        fitter = TorchGradientLatentMapFitter(
            IdentityFieldEncoder(3, torch_bkd),
            IdentityFieldEncoder(2, torch_bkd, is_isometry=False),
            torch_bkd,
        )
        with pytest.raises(ValueError, match="isometry"):
            fitter.fit_encoded(
                MLPLatentMap(3, 2, [], torch_bkd), codes_in, codes_out
            )

    def test_allow_proxy_accepts_one(self, torch_bkd: Backend) -> None:
        codes_in, codes_out, _, _ = _affine_data(torch_bkd)
        fitter = TorchGradientLatentMapFitter(
            IdentityFieldEncoder(3, torch_bkd),
            IdentityFieldEncoder(2, torch_bkd, is_isometry=False),
            torch_bkd,
            optimizer=torch_adam(nsteps=10),
            allow_proxy=True,
        )
        surrogate = fitter.fit_encoded(
            MLPLatentMap(3, 2, [], torch_bkd), codes_in, codes_out
        )
        assert surrogate(codes_in).shape == (2, 200)

    def test_rejects_a_map_with_no_parameters(
        self, torch_bkd: Backend
    ) -> None:
        """Nothing to optimize is a mistake, not a no-op fit."""

        class _Parameterless(torch.nn.Module):
            def nvars(self) -> int:
                return 3

            def nqoi(self) -> int:
                return 2

            def forward(self, coefs):
                return coefs[:2]

        codes_in, codes_out, _, _ = _affine_data(torch_bkd)
        with pytest.raises(ValueError, match="no trainable"):
            _fitter(torch_bkd).fit_encoded(
                _Parameterless(), codes_in, codes_out
            )

    def test_rejects_mismatched_sample_counts(
        self, torch_bkd: Backend
    ) -> None:
        codes_in, codes_out, _, _ = _affine_data(torch_bkd)
        with pytest.raises(ValueError, match="realizations"):
            _fitter(torch_bkd).fit_encoded(
                MLPLatentMap(3, 2, [], torch_bkd),
                codes_in,
                codes_out[:, :10],
            )

    def test_rejects_bad_batch_size(self, torch_bkd: Backend) -> None:
        with pytest.raises(ValueError, match="batch_size"):
            _fitter(torch_bkd, batch_size=0)

    def test_rejects_a_non_spec_optimizer(
        self, torch_bkd: Backend
    ) -> None:
        with pytest.raises(TypeError, match="TorchOptimizerSpecProtocol"):
            _fitter(torch_bkd, optimizer="adam")
