r"""Tests for fitting a latent map by gradient descent.

The load-bearing test is the equivalence one: this fitter and the
closed-form solver minimize the *same* objective, differing only in how
they reach it, so on a map that is linear in its parameters they must
arrive at the same place. That checks the optimizer against an exact
reference rather than against a tolerance someone chose by running it.

The rest pin what the optimizer seam buys -- that a different
``torch.optim`` class can be chosen without a new fitter, and that
chaining a polish after a first-order stage is expressible.
"""

import numpy as np
import pytest
import torch
from pyapprox.surrogates.operatorlearning import (
    IdentityFieldEncoder,
    WeightedLeastSquaresOperatorFitter,
)
from pyapprox.surrogates.operatorlearning.latent_maps import (
    ChainedTorchOptimizer,
    MLPLatentMap,
    TorchGradientLatentMapFitter,
    TorchOptimizerSpec,
    torch_adam,
    torch_lbfgs,
)
from pyapprox.util.backends.numpy import NumpyBkd
from pyapprox.util.backends.protocols import Backend


def _affine_data(bkd: Backend, nsamples: int = 200, seed: int = 0):
    """Data generated by an affine map, so a least-squares fit is exact."""
    rng = np.random.RandomState(seed)
    matrix = rng.normal(0.0, 1.0, (2, 3))
    offset = rng.normal(0.0, 1.0, (2, 1))
    codes_in = rng.uniform(-1.0, 1.0, (3, nsamples))
    codes_out = matrix @ codes_in + offset
    return (
        bkd.asarray(codes_in),
        bkd.asarray(codes_out),
        matrix,
        offset,
    )


def _fitter(torch_bkd: Backend, optimizer=None, **kwargs):
    return TorchGradientLatentMapFitter(
        IdentityFieldEncoder(3, torch_bkd),
        IdentityFieldEncoder(2, torch_bkd),
        torch_bkd,
        optimizer=optimizer,
        seed=0,
        **kwargs,
    )


def _max_residual(bkd: Backend, surrogate, codes_in, codes_out) -> float:
    return float(bkd.max(bkd.abs(surrogate(codes_in) - codes_out)))


class TestAgreementWithTheClosedFormSolver:
    r"""Same objective, two routes to it, so they must agree.

    Both minimize :math:`\sum_i \|g(\hat f^i) - \hat g^i\|_2^2`. One
    solves it directly, the other descends. On a latent map that is
    linear in its parameters the minimizer is unique, so a gradient fit
    that has converged reaches it -- and that is what makes this an
    exact check rather than a tolerance.
    """

    def test_recovers_the_generating_map(
        self, torch_bkd: Backend
    ) -> None:
        """An affine map on affine data: the fit should be exact."""
        codes_in, codes_out, matrix, _ = _affine_data(torch_bkd)
        surrogate = _fitter(torch_bkd).fit_encoded(
            MLPLatentMap(3, 2, [], torch_bkd), codes_in, codes_out
        ).surrogate()
        assert (
            _max_residual(torch_bkd, surrogate, codes_in, codes_out)
            < 1e-8
        )
        weight = next(surrogate.latent_map().parameters())
        torch_bkd.assert_allclose(
            weight, torch_bkd.asarray(matrix), atol=1e-8
        )

    def test_matches_least_squares_on_inconsistent_data(
        self, torch_bkd: Backend
    ) -> None:
        """The case with no exact solution, where the two could differ.

        With data outside the affine span there is a unique minimizer
        rather than an interpolant, so agreeing on it is a stronger
        claim than agreeing on a residual both drive to zero. The
        reference is the closed-form solver's own answer on the same
        data.
        """
        rng = np.random.RandomState(1)
        codes_in = torch_bkd.asarray(rng.uniform(-1.0, 1.0, (3, 120)))
        # Quadratic targets cannot be represented by an affine map.
        squared = torch_bkd.to_numpy(codes_in) ** 2
        codes_out = torch_bkd.asarray(squared[:2] + 0.5 * squared[1:])

        gradient_fit = _fitter(torch_bkd).fit_encoded(
            MLPLatentMap(3, 2, [], torch_bkd), codes_in, codes_out
        ).surrogate()

        reference = _least_squares_affine_fit(
            torch_bkd, codes_in, codes_out
        )
        # Looser than the exactly-fittable case above, and not because
        # of a tolerance -- tightening the optimizer's changes nothing
        # here. The minimizer itself sits at a nonzero residual, so the
        # gradient a descent method follows never vanishes and it
        # settles near the solution rather than on it. A closed-form
        # solve has no such limit, which is why it is the reference
        # rather than the peer.
        torch_bkd.assert_allclose(
            gradient_fit(codes_in), reference, atol=1e-5
        )


def _least_squares_affine_fit(bkd: Backend, codes_in, codes_out):
    """Return the closed-form affine least-squares prediction.

    Uses the package's own solver over a degree-one expansion rather
    than a hand-rolled normal-equation solve, so the comparison is
    against the code that ships.
    """
    from pyapprox.probability import UniformMarginal
    from pyapprox.surrogates.affine.basis.orthonormal_poly import (
        OrthonormalPolynomialBasis,
    )
    from pyapprox.surrogates.affine.expansions.pce import (
        PolynomialChaosExpansion,
    )
    from pyapprox.surrogates.affine.univariate.factory import (
        create_bases_1d,
    )

    nvars = int(codes_in.shape[0])
    marginals = [UniformMarginal(-1.0, 1.0, bkd) for _ in range(nvars)]
    basis = OrthonormalPolynomialBasis(
        create_bases_1d(marginals, bkd), bkd
    )
    indices = np.vstack(
        [np.zeros((1, nvars), dtype=int), np.eye(nvars, dtype=int)]
    ).T
    basis.set_indices(bkd.asarray(indices, dtype=bkd.int64_dtype()))
    expansion = PolynomialChaosExpansion(
        basis, bkd, nqoi=int(codes_out.shape[0])
    )
    result = WeightedLeastSquaresOperatorFitter(
        IdentityFieldEncoder(nvars, bkd),
        IdentityFieldEncoder(int(codes_out.shape[0]), bkd),
        bkd,
    ).fit_encoded(expansion, codes_in, codes_out)
    return result.surrogate()(codes_in)


class TestTheOptimizerSeam:
    """Any torch optimizer drives the fitter, with no new fitter class.

    These check that each spec *runs and produces a usable surrogate* --
    nothing about which optimizer does better. Comparing optimizers
    against each other would assert a numerical accident rather than a
    contract: on a problem with an exact solution several of them
    converge to within rounding of each other, so any ordering between
    them is noise that a library change could legitimately flip.
    """

    @pytest.mark.parametrize(
        "optimizer",
        [
            torch_adam(learning_rate=0.05, nsteps=2000),
            torch_lbfgs(nsteps=2000),
            ChainedTorchOptimizer(
                [torch_adam(nsteps=500), torch_lbfgs(nsteps=500)]
            ),
            TorchOptimizerSpec(
                torch.optim.SGD, nsteps=2000, lr=1e-3, momentum=0.9
            ),
        ],
        ids=["adam", "lbfgs", "chained", "sgd_momentum"],
    )
    def test_each_spec_produces_a_usable_surrogate(
        self, torch_bkd: Backend, optimizer
    ) -> None:
        """Including SGD, whose ``momentum`` Adam's signature lacks.

        That parameter is the point of taking a spec: a fitter exposing
        per-optimizer knobs directly could not express it without
        growing a union of every optimizer's arguments.
        """
        codes_in, codes_out, _, _ = _affine_data(torch_bkd)
        result = _fitter(
            torch_bkd, optimizer=optimizer
        ).fit_encoded(
            MLPLatentMap(3, 2, [], torch_bkd), codes_in, codes_out
        )
        surrogate = result.surrogate()
        assert surrogate(codes_in).shape == (2, 200)
        # Usable, not optimal: every spec here should get most of the
        # way on data an affine map fits exactly, while none is required
        # to beat any other.
        assert (
            _max_residual(torch_bkd, surrogate, codes_in, codes_out)
            < 1e-2
        )

    def test_the_reported_loss_covers_every_sample(
        self, torch_bkd: Backend
    ) -> None:
        """Not just the last mini-batch a stage happened to draw.

        A batched stage sees a different subset each step, so a loss read
        off one of them is a random sample of the objective rather than
        the objective. Compared against the loss recomputed here over the
        full data, which is the quantity a caller means by "the loss".
        """
        codes_in, codes_out, _, _ = _affine_data(torch_bkd)
        result = _fitter(
            torch_bkd,
            optimizer=torch_adam(nsteps=300),
            batch_size=16,
        ).fit_encoded(
            MLPLatentMap(3, 2, [], torch_bkd), codes_in, codes_out
        )
        predicted = result.surrogate()(codes_in)
        full_sample_loss = float(
            torch_bkd.sum((predicted - codes_out) ** 2)
        )
        torch_bkd.assert_allclose(
            torch_bkd.asarray([result.fun()]),
            torch_bkd.asarray([full_sample_loss]),
            rtol=1e-10,
        )

    def test_the_result_reports_how_each_stage_ended(
        self, torch_bkd: Backend
    ) -> None:
        """One record per stage, which is what makes a fit diagnosable.

        Whether a remaining error is the model's limit or the iteration
        budget's has different fixes, and these records are how a caller
        tells them apart.
        """
        codes_in, codes_out, _, _ = _affine_data(torch_bkd)
        # A short first stage on purpose. With the default budget Adam
        # reaches machine precision alone, L-BFGS then meets its gradient
        # tolerance without stepping, and the polish records no work --
        # so the handoff the chain exists for would go untested.
        optimizer = ChainedTorchOptimizer(
            [torch_adam(nsteps=200), torch_lbfgs(nsteps=2000)]
        )
        result = _fitter(torch_bkd, optimizer=optimizer).fit_encoded(
            MLPLatentMap(3, 2, [], torch_bkd), codes_in, codes_out
        )
        adam, lbfgs = result.stages()
        assert [adam.name(), lbfgs.name()] == ["Adam", "LBFGS"]

        # Both terminations occur here, which is why they are worth
        # asserting rather than a bare invariant. Adam has no
        # convergence test, so it always runs its budget out; L-BFGS
        # stops on a tolerance well inside its own.
        assert adam.exhausted_budget()
        assert adam.niterations() == adam.maxiterations()
        assert not lbfgs.exhausted_budget()
        assert 0 < lbfgs.niterations() < lbfgs.maxiterations()

        # The polish earns its place: it takes a loss the first stage
        # left far from zero down to near it. This also pins the loss to
        # the value *after* each stage -- torch's ``step`` returns the
        # closure's first evaluation, which predates the step entirely.
        assert adam.fun() > 1e-3
        assert lbfgs.fun() < 1e-6

        # The fit as a whole is judged by its last stage, so a
        # first-order stage running out does not make it a failure.
        assert result.success()
        assert result.fun() == lbfgs.fun()
        assert "converged" in result.message()


class TestLeavesItsArgumentAlone:
    def test_fits_a_copy(self, torch_bkd: Backend) -> None:
        """So one untrained map can seed several fits."""
        codes_in, codes_out, _, _ = _affine_data(torch_bkd)
        template = MLPLatentMap(3, 2, [], torch_bkd)
        before = next(template.parameters()).detach().clone()
        surrogate = _fitter(torch_bkd).fit_encoded(
            template, codes_in, codes_out
        ).surrogate()
        torch_bkd.assert_allclose(
            next(template.parameters()), before, atol=0.0
        )
        assert surrogate.latent_map() is not template


class TestRejects:
    def test_rejects_a_non_torch_backend(self) -> None:
        with pytest.raises(TypeError, match="TorchBkd"):
            TorchGradientLatentMapFitter(
                IdentityFieldEncoder(3, NumpyBkd()),
                IdentityFieldEncoder(2, NumpyBkd()),
                NumpyBkd(),
            )

    def test_rejects_a_non_isometric_output_encoder(
        self, torch_bkd: Backend
    ) -> None:
        """This fitter reads a coefficient residual as a field error."""
        codes_in, codes_out, _, _ = _affine_data(torch_bkd)
        fitter = TorchGradientLatentMapFitter(
            IdentityFieldEncoder(3, torch_bkd),
            IdentityFieldEncoder(2, torch_bkd, is_isometry=False),
            torch_bkd,
        )
        with pytest.raises(ValueError, match="isometry"):
            fitter.fit_encoded(
                MLPLatentMap(3, 2, [], torch_bkd), codes_in, codes_out
            )

    def test_allow_proxy_accepts_one(self, torch_bkd: Backend) -> None:
        codes_in, codes_out, _, _ = _affine_data(torch_bkd)
        fitter = TorchGradientLatentMapFitter(
            IdentityFieldEncoder(3, torch_bkd),
            IdentityFieldEncoder(2, torch_bkd, is_isometry=False),
            torch_bkd,
            optimizer=torch_adam(nsteps=10),
            allow_proxy=True,
        )
        surrogate = fitter.fit_encoded(
            MLPLatentMap(3, 2, [], torch_bkd), codes_in, codes_out
        ).surrogate()
        assert surrogate(codes_in).shape == (2, 200)

    def test_rejects_a_map_with_no_parameters(
        self, torch_bkd: Backend
    ) -> None:
        """Nothing to optimize is a mistake, not a no-op fit."""

        class _Parameterless(torch.nn.Module):
            def nvars(self) -> int:
                return 3

            def nqoi(self) -> int:
                return 2

            def forward(self, coefs):
                return coefs[:2]

        codes_in, codes_out, _, _ = _affine_data(torch_bkd)
        with pytest.raises(ValueError, match="no trainable"):
            _fitter(torch_bkd).fit_encoded(
                _Parameterless(), codes_in, codes_out
            )

    def test_rejects_mismatched_sample_counts(
        self, torch_bkd: Backend
    ) -> None:
        codes_in, codes_out, _, _ = _affine_data(torch_bkd)
        with pytest.raises(ValueError, match="realizations"):
            _fitter(torch_bkd).fit_encoded(
                MLPLatentMap(3, 2, [], torch_bkd),
                codes_in,
                codes_out[:, :10],
            )

    def test_rejects_bad_batch_size(self, torch_bkd: Backend) -> None:
        with pytest.raises(ValueError, match="batch_size"):
            _fitter(torch_bkd, batch_size=0)

    def test_rejects_a_non_spec_optimizer(
        self, torch_bkd: Backend
    ) -> None:
        with pytest.raises(TypeError, match="TorchOptimizerSpecProtocol"):
            _fitter(torch_bkd, optimizer="adam")
