"""Tests for operator-learning fitting and the surrogate.

Terminology: a *realization* is one draw of the input field. Encoded,
it is a column of ``coefs_in`` with one entry per input basis function.
These are not points in the spatial domain of the field.
"""

from typing import Any, Tuple

import numpy as np
import pytest
from pyapprox.ode.mass_matrix import DiagonalMassMatrix
from pyapprox.probability import UniformMarginal
from pyapprox.surrogates.affine.basis.orthonormal_poly import (
    OrthonormalPolynomialBasis,
)
from pyapprox.surrogates.affine.expansions.pce import (
    PolynomialChaosExpansion,
)
from pyapprox.surrogates.affine.indices.utils import (
    compute_hyperbolic_indices,
)
from pyapprox.surrogates.affine.univariate.factory import create_bases_1d
from pyapprox.surrogates.operatorlearning import (
    GramProjectionEncoder,
    IdentityFieldEncoder,
    OperatorSurrogate,
    WeightedLeastSquaresOperatorFitter,
    bochner_error,
)
from pyapprox.util.backends.protocols import Backend


def _expansion(
    bkd: Backend, nvars: int, max_level: int, noutputs: int
) -> PolynomialChaosExpansion:
    """Legendre expansion on [-1, 1]^nvars with a total-degree index set."""
    marginals = [UniformMarginal(-1.0, 1.0, bkd) for _ in range(nvars)]
    basis = OrthonormalPolynomialBasis(create_bases_1d(marginals, bkd), bkd)
    basis.set_indices(compute_hyperbolic_indices(nvars, max_level, 1.0, bkd))
    return PolynomialChaosExpansion(basis, bkd, nqoi=noutputs)


def _linear_expansion(
    bkd: Backend, nvars: int, noutputs: int
) -> PolynomialChaosExpansion:
    """Expansion whose index set is the pure first-order terms {e_j}.

    For this set every basis function is degree one in one coordinate,
    so the surrogate is linear and its coefficients form a matrix.
    """
    marginals = [UniformMarginal(-1.0, 1.0, bkd) for _ in range(nvars)]
    basis = OrthonormalPolynomialBasis(create_bases_1d(marginals, bkd), bkd)
    basis.set_indices(
        bkd.asarray(np.eye(nvars, dtype=int), dtype=bkd.int64_dtype())
    )
    return PolynomialChaosExpansion(basis, bkd, nqoi=noutputs)


def _affine_expansion(
    bkd: Backend, nvars: int, noutputs: int
) -> PolynomialChaosExpansion:
    """Expansion over the constant plus the first-order terms.

    The affine case: a constant offset alongside a linear map.
    """
    marginals = [UniformMarginal(-1.0, 1.0, bkd) for _ in range(nvars)]
    basis = OrthonormalPolynomialBasis(create_bases_1d(marginals, bkd), bkd)
    indices = np.vstack(
        [np.zeros((1, nvars), dtype=int), np.eye(nvars, dtype=int)]
    ).T
    basis.set_indices(bkd.asarray(indices, dtype=bkd.int64_dtype()))
    return PolynomialChaosExpansion(basis, bkd, nqoi=noutputs)


def _identity_fitter(
    bkd: Backend, ncodes_in: int, ncodes_out: int
) -> WeightedLeastSquaresOperatorFitter:
    """Fitter over identity encoders, for tests working in coefficients."""
    return WeightedLeastSquaresOperatorFitter(
        IdentityFieldEncoder(ncodes_in, bkd),
        IdentityFieldEncoder(ncodes_out, bkd),
        bkd,
    )


def _sine_encoder(bkd: Backend, ngrid: int, ncodes: int) -> Any:
    """Orthonormal sine basis with its quadrature inner product."""
    x = np.linspace(0.0, 1.0, ngrid + 2)[1:-1]
    modes = np.arange(1, ncodes + 1)
    sine = np.sqrt(2.0) * np.sin(np.outer(x, modes) * np.pi)
    mass = DiagonalMassMatrix(bkd.full((ngrid,), 1.0 / (ngrid + 1)), bkd)
    return GramProjectionEncoder(bkd.asarray(sine), mass, bkd)


def _decaying_realizations(
    bkd: Backend, ncodes: int, nsamples: int
) -> Tuple[Any, Any]:
    """Realizations with a KLE-like decaying spectrum.

    Coefficients drawn uniformly would give white-noise fields, which
    no operator learning problem produces. Scaling mode k by 1/k gives
    the decaying spectrum a Karhunen-Loeve expansion produces, so the
    realizations are smooth.

    Returns the coefficients both scaled (the realizations) and raw
    (the expansion variables, which must stay in [-1, 1]).
    """
    raw = np.random.uniform(-1.0, 1.0, (ncodes, nsamples))
    decay = 1.0 / np.arange(1, ncodes + 1)
    return bkd.asarray(decay[:, None] * raw), bkd.asarray(raw)


class TestWeightedLeastSquaresOperatorFitter:
    def test_recovers_synthetic_operator(self, bkd: Backend) -> None:
        """T7: exact recovery of a target built from the basis itself.

        No PDE: the data is generated by the expansion, so both the
        coefficients and the predicted outputs must come back exactly.
        """
        np.random.seed(0)
        expansion = _expansion(bkd, 2, 3, 4)
        true_params = bkd.asarray(
            np.random.normal(0.0, 1.0, (expansion.nterms(), 4))
        )
        coefs_in = bkd.asarray(np.random.uniform(-1.0, 1.0, (2, 200)))
        coefs_out = expansion.with_params(true_params)(coefs_in)

        result = _identity_fitter(bkd, 2, 4).fit_encoded(
            expansion, coefs_in, coefs_out
        )
        bkd.assert_allclose(result.params(), true_params, atol=1e-11)
        # The prediction is the claim that matters, not just the params.
        bkd.assert_allclose(
            result.surrogate()(coefs_in), coefs_out, atol=1e-11
        )

    def test_recovers_with_weights(self, bkd: Backend) -> None:
        """Weighting changes the estimator but not an exact in-span fit."""
        np.random.seed(0)
        expansion = _expansion(bkd, 2, 3, 4)
        true_params = bkd.asarray(
            np.random.normal(0.0, 1.0, (expansion.nterms(), 4))
        )
        coefs_in = bkd.asarray(np.random.uniform(-1.0, 1.0, (2, 200)))
        coefs_out = expansion.with_params(true_params)(coefs_in)
        weights = bkd.asarray(np.random.uniform(0.5, 2.0, (200,)))

        result = _identity_fitter(bkd, 2, 4).fit_encoded(
            expansion, coefs_in, coefs_out, weights=weights
        )
        bkd.assert_allclose(result.params(), true_params, atol=1e-11)

    def test_weights_change_an_overdetermined_fit(self, bkd: Backend) -> None:
        """With data outside the span, weighting must change the answer.

        Guards against weights being accepted and then ignored, which
        an in-span test cannot detect.
        """
        np.random.seed(0)
        expansion = _expansion(bkd, 2, 1, 1)
        coefs_in = bkd.asarray(np.random.uniform(-1.0, 1.0, (2, 50)))
        # Quadratic data cannot be represented by a linear expansion.
        squared = bkd.to_numpy(coefs_in)[0] ** 2
        coefs_out = bkd.asarray(squared[None, :])
        weights = bkd.asarray(np.linspace(0.1, 10.0, 50))

        fitter = _identity_fitter(bkd, 2, 1)
        unweighted = fitter.fit_encoded(expansion, coefs_in, coefs_out)
        weighted = fitter.fit_encoded(
            expansion, coefs_in, coefs_out, weights=weights
        )
        difference = float(
            bkd.max(bkd.abs(unweighted.params() - weighted.params()))
        )
        assert difference > 1e-6

    def test_operator_matrix_recovers_a_dense_linear_map(
        self, bkd: Backend
    ) -> None:
        """T6: an arbitrary linear operator is recovered exactly.

        The operator here is dense, so passing requires recovering
        every cross-mode coupling rather than merely preserving a
        structure the test imposed.
        """
        np.random.seed(0)
        nvars = 4
        operator = np.random.normal(0.0, 1.0, (nvars, nvars))
        expansion = _linear_expansion(bkd, nvars, nvars)
        coefs_in = bkd.asarray(np.random.uniform(-1.0, 1.0, (nvars, 200)))
        coefs_out = bkd.asarray(operator @ bkd.to_numpy(coefs_in))

        result = _identity_fitter(bkd, nvars, nvars).fit_encoded(
            expansion, coefs_in, coefs_out
        )
        # Legendre degree one is sqrt(3) x, so Phi = sqrt(3) * coefs_in
        # and the fitted C satisfies sqrt(3) C^T = operator.
        matrix = bkd.to_numpy(result.operator_matrix())
        expected = (operator / np.sqrt(3.0)).T
        assert np.max(np.abs(matrix - expected)) < 1e-11

    def test_operator_matrix_of_a_diagonal_operator_is_diagonal(
        self, bkd: Backend
    ) -> None:
        """T6: an operator diagonal in the bases has no cross terms.

        The inverse Laplacian in a sine basis is the motivating case:
        sines are its eigenfunctions, so input mode n produces output
        mode n alone with eigenvalue -1/(pi^2 n^2). Recovering zero
        off-diagonal entries shows the fit invents no couplings the
        operator does not have.
        """
        np.random.seed(0)
        nvars = 4
        eigenvalues = np.array(
            [-1.0 / (np.pi**2 * (n + 1) ** 2) for n in range(nvars)]
        )
        expansion = _linear_expansion(bkd, nvars, nvars)
        coefs_in = bkd.asarray(np.random.uniform(-1.0, 1.0, (nvars, 200)))
        coefs_out = bkd.asarray(
            eigenvalues[:, None] * bkd.to_numpy(coefs_in)
        )

        result = _identity_fitter(bkd, nvars, nvars).fit_encoded(
            expansion, coefs_in, coefs_out
        )
        matrix = bkd.to_numpy(result.operator_matrix())
        bkd.assert_allclose(
            bkd.asarray(np.diag(matrix)),
            bkd.asarray(eigenvalues / np.sqrt(3.0)),
            atol=1e-12,
        )
        off_diagonal = matrix - np.diag(np.diag(matrix))
        assert np.max(np.abs(off_diagonal)) < 1e-12

    def test_recovers_an_affine_operator(self, bkd: Backend) -> None:
        """T6: a map with an offset splits into matrix and intercept.

        A constant term is ordinary — any operator with a nonzero
        response to zero input has one — so it is admitted, but kept
        separate from the matrix rows since the two mean different
        things.
        """
        np.random.seed(0)
        nvars = 3
        operator = np.random.normal(0.0, 1.0, (nvars, nvars))
        offset = np.random.normal(0.0, 1.0, (nvars,))
        expansion = _affine_expansion(bkd, nvars, nvars)
        coefs_in = bkd.asarray(np.random.uniform(-1.0, 1.0, (nvars, 200)))
        coefs_out = bkd.asarray(
            operator @ bkd.to_numpy(coefs_in) + offset[:, None]
        )

        result = _identity_fitter(bkd, nvars, nvars).fit_encoded(
            expansion, coefs_in, coefs_out
        )
        matrix = bkd.to_numpy(result.operator_matrix())
        assert matrix.shape == (nvars, nvars)
        assert np.max(np.abs(matrix - (operator / np.sqrt(3.0)).T)) < 1e-11
        # Legendre degree zero is the constant one, so b is recovered
        # directly rather than scaled.
        recovered = result.intercept()
        assert recovered is not None
        bkd.assert_allclose(recovered, bkd.asarray(offset), atol=1e-11)

    def test_intercept_is_none_without_a_constant_term(
        self, bkd: Backend
    ) -> None:
        """A strictly linear index set has no intercept to report."""
        np.random.seed(0)
        expansion = _linear_expansion(bkd, 3, 3)
        coefs_in = bkd.asarray(np.random.uniform(-1.0, 1.0, (3, 100)))
        coefs_out = bkd.asarray(np.random.normal(0.0, 1.0, (3, 100)))
        result = _identity_fitter(bkd, 3, 3).fit_encoded(
            expansion, coefs_in, coefs_out
        )
        assert result.intercept() is None

    def test_operator_matrix_excludes_the_constant_row(
        self, bkd: Backend
    ) -> None:
        """The matrix has one row per input, not one per basis term."""
        np.random.seed(0)
        nvars = 3
        expansion = _affine_expansion(bkd, nvars, 2)
        coefs_in = bkd.asarray(np.random.uniform(-1.0, 1.0, (nvars, 100)))
        coefs_out = bkd.asarray(np.random.normal(0.0, 1.0, (2, 100)))
        result = _identity_fitter(bkd, nvars, 2).fit_encoded(
            expansion, coefs_in, coefs_out
        )
        assert expansion.nterms() == nvars + 1
        assert result.operator_matrix().shape == (nvars, 2)

    def test_operator_matrix_rejects_nonlinear_index_set(
        self, bkd: Backend
    ) -> None:
        """No matrix represents a surrogate with higher-order terms."""
        np.random.seed(0)
        expansion = _expansion(bkd, 2, 3, 2)
        coefs_in = bkd.asarray(np.random.uniform(-1.0, 1.0, (2, 50)))
        coefs_out = bkd.asarray(np.random.normal(0.0, 1.0, (2, 50)))
        result = _identity_fitter(bkd, 2, 2).fit_encoded(
            expansion, coefs_in, coefs_out
        )
        with pytest.raises(ValueError, match="first order"):
            result.operator_matrix()
        with pytest.raises(ValueError, match="first order"):
            result.intercept()

    def test_original_expansion_unchanged(self, bkd: Backend) -> None:
        """Fitting follows the immutable pattern."""
        np.random.seed(0)
        expansion = _expansion(bkd, 2, 2, 3)
        before = bkd.to_numpy(expansion.get_coefficients()).copy()
        coefs_in = bkd.asarray(np.random.uniform(-1.0, 1.0, (2, 100)))
        coefs_out = bkd.asarray(np.random.normal(0.0, 1.0, (3, 100)))
        _identity_fitter(bkd, 2, 3).fit_encoded(
            expansion, coefs_in, coefs_out
        )
        after = bkd.to_numpy(expansion.get_coefficients())
        assert np.array_equal(before, after)

    def test_rejects_1d_outputs(self, bkd: Backend) -> None:
        expansion = _expansion(bkd, 2, 2, 1)
        coefs_in = bkd.asarray(np.random.uniform(-1.0, 1.0, (2, 10)))
        with pytest.raises(ValueError, match="must be 2D"):
            _identity_fitter(bkd, 2, 1).fit_encoded(
                expansion, coefs_in, bkd.zeros((10,))
            )

    def test_rejects_realization_count_mismatch(self, bkd: Backend) -> None:
        expansion = _expansion(bkd, 2, 2, 3)
        coefs_in = bkd.asarray(np.random.uniform(-1.0, 1.0, (2, 10)))
        with pytest.raises(ValueError, match="realizations"):
            _identity_fitter(bkd, 2, 3).fit_encoded(
                expansion, coefs_in, bkd.zeros((3, 9))
            )

    def test_rejects_wrong_weight_shape(self, bkd: Backend) -> None:
        expansion = _expansion(bkd, 2, 2, 3)
        coefs_in = bkd.asarray(np.random.uniform(-1.0, 1.0, (2, 10)))
        with pytest.raises(ValueError, match="wrong shape"):
            _identity_fitter(bkd, 2, 3).fit_encoded(
                expansion, coefs_in, bkd.zeros((3, 10)), weights=bkd.ones((9,))
            )

    def test_rejects_non_encoder(self, bkd: Backend) -> None:
        with pytest.raises(TypeError, match="FieldEncoderProtocol"):
            WeightedLeastSquaresOperatorFitter(
                "not_an_encoder", IdentityFieldEncoder(3, bkd), bkd
            )


class TestFitFromFields:
    """End-to-end fits from field realizations, not coefficients."""

    def test_recovers_an_unknown_diagonal_operator(
        self, numpy_bkd: Backend
    ) -> None:
        """Fit smooth fields produced by an operator the fitter is not told.

        The data is generated by applying a known operator to smooth
        realizations, then handed over as fields alone. Success means
        the predicted output *fields* match the truth, measured in the
        Bochner norm the isometric encoder makes meaningful.
        """
        np.random.seed(0)
        ngrid, ncodes = 64, 5
        encoder = _sine_encoder(numpy_bkd, ngrid, ncodes)
        assert encoder.is_isometry()

        # The operator: an inverse-Laplacian-like diagonal map, known
        # here only to build the data.
        eigenvalues = np.array(
            [-1.0 / (np.pi**2 * (n + 1) ** 2) for n in range(ncodes)]
        )
        coefs_in, _ = _decaying_realizations(numpy_bkd, ncodes, 400)
        coefs_out = numpy_bkd.asarray(
            eigenvalues[:, None] * numpy_bkd.to_numpy(coefs_in)
        )

        input_fields = encoder.decode(coefs_in)
        output_fields = encoder.decode(coefs_out)

        # The expansion's variables are the raw coefficients, which the
        # basis expects in [-1, 1]; the decaying scale is part of the
        # operator being learned.
        expansion = _linear_expansion(numpy_bkd, ncodes, ncodes)
        fitter = WeightedLeastSquaresOperatorFitter(
            encoder, encoder, numpy_bkd
        )
        result = fitter.fit_encoded(expansion, coefs_in, coefs_out)

        predicted_fields = result.surrogate()(input_fields)
        error = bochner_error(
            encoder.encode(predicted_fields),
            encoder.encode(output_fields),
            numpy_bkd,
        )
        assert error < 1e-10

    def test_fit_from_fields_matches_fit_encoded(
        self, numpy_bkd: Backend
    ) -> None:
        """fit() is exactly fit_encoded() with the encoding done first."""
        np.random.seed(0)
        ngrid, ncodes = 64, 4
        encoder = _sine_encoder(numpy_bkd, ngrid, ncodes)
        coefs_in, _ = _decaying_realizations(numpy_bkd, ncodes, 200)
        operator = np.random.normal(0.0, 1.0, (ncodes, ncodes))
        coefs_out = numpy_bkd.asarray(
            operator @ numpy_bkd.to_numpy(coefs_in)
        )

        expansion = _linear_expansion(numpy_bkd, ncodes, ncodes)
        fitter = WeightedLeastSquaresOperatorFitter(
            encoder, encoder, numpy_bkd
        )
        from_fields = fitter.fit(
            expansion, encoder.decode(coefs_in), encoder.decode(coefs_out)
        )
        from_coefs = fitter.fit_encoded(expansion, coefs_in, coefs_out)
        numpy_bkd.assert_allclose(
            from_fields.params(), from_coefs.params(), atol=1e-10
        )


class TestOperatorSurrogate:
    def test_output_shape(self, bkd: Backend) -> None:
        expansion = _expansion(bkd, 2, 2, 3)
        surrogate = OperatorSurrogate(
            IdentityFieldEncoder(2, bkd),
            IdentityFieldEncoder(3, bkd),
            expansion,
            bkd,
        )
        fields = bkd.asarray(np.random.uniform(-1.0, 1.0, (2, 7)))
        assert surrogate(fields).shape == (3, 7)

    def test_rejects_non_isometric_output_encoder(self, bkd: Backend) -> None:
        """The Bochner identity fails silently without this check."""
        expansion = _expansion(bkd, 2, 2, 3)
        with pytest.raises(ValueError, match="isometry"):
            OperatorSurrogate(
                IdentityFieldEncoder(2, bkd),
                IdentityFieldEncoder(3, bkd, is_isometry=False),
                expansion,
                bkd,
            )

    def test_rejects_output_code_mismatch(self, bkd: Backend) -> None:
        expansion = _expansion(bkd, 2, 2, 3)
        with pytest.raises(ValueError, match="nqoi"):
            OperatorSurrogate(
                IdentityFieldEncoder(2, bkd),
                IdentityFieldEncoder(5, bkd),
                expansion,
                bkd,
            )

    def test_rejects_input_code_mismatch(self, bkd: Backend) -> None:
        expansion = _expansion(bkd, 2, 2, 3)
        with pytest.raises(ValueError, match="nvars"):
            OperatorSurrogate(
                IdentityFieldEncoder(5, bkd),
                IdentityFieldEncoder(3, bkd),
                expansion,
                bkd,
            )

    def test_rejects_non_encoder(self, bkd: Backend) -> None:
        expansion = _expansion(bkd, 2, 2, 3)
        with pytest.raises(TypeError, match="FieldEncoderProtocol"):
            OperatorSurrogate(
                "not_an_encoder", IdentityFieldEncoder(3, bkd), expansion, bkd
            )
