name: Build Docs Using Pip

on:
  # push:
  # branches: [master]
  # branches: [master, devel]
  pull_request:
    branches: [devel]

  workflow_dispatch:


#   # schedule:
#   #  # * is a special character in YAML so you have to quote this string
#   #  - cron:  '*/0 * * * *' # run once a day


jobs:
  pyapprox_unit_tests:
    name: Build docs with pip-build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest]
        python-version: [3.9, '3.10', '3.11']
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Setup PyApprox Documentation
        shell: bash -l {0}
        run: |
          python -m pip install -e .[docs]
      - name: Create PyApprox Documentation
        shell: bash -l {0}
        run: |
          cd docs
          make html SPHINXOPTS=-vvv
